### ISSUE TITLE
New version for Trovo and Facebook

### ISSUE THREAD

**Issue by JorkDev** [iiiklox/niconico-twitch#2]
A good idea about this tool would be to expand on other streaming platforms, keep the same concept but now take it to a new level.
Since **Trovo** is taking a very large field in this area of **Streaming**, and surely people will look to have the chat with this aesthetic.

**Comment by ThatKoffe** [comment]
love this

**Comment by tekigg** [comment]
We'd definitely love to support more platforms! Thank you for your suggestions.
